short_name: "Tri Do"
full_name: "Tri Do Nguyen"

email: 'tridonguyen392@gmail.com'


short_intro: "I create things for the mobile using Android and Flutter"
long_intro: |
  I'm a freelancer based in HoChiMinh City, VietNam.
  I'm passionate about developing creative and valuable apps that makes this world better.